version: 2.1

jobs:
    build:
        docker:
            - image: circleci/android:api-30-ndk

        steps:
            - checkout

            - run:
                name: Restore google-services.json
                command: echo $GOOGLE_SERVICES_JSON > ${HOME}/WebViewWindow/src/debug/google-services.json

            - run:
                name: Run Build
                command: ./gradlew assemble

    test:
        docker:
            - image: circleci/android:api-30-ndk

        steps:
            - checkout

            - run:
                name: Run Test
                command: ./gradlew test

            - run:
                name: Run Lint
                command: ./gradlew lint

            - store_artifacts:
                path: build/reports

            - store_test_results:
                path: build/reports

workflows:
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                    - build
