version: 2.1

defaults: &defaults
    working_directory: /tmp/workspace
    docker:
          - image: cimg/android:2023.06.1-ndk

jobs:
    sync:
        <<: *defaults

        steps:
            - checkout

            - run:
                  name: Restore google-services.json
                  command: |
                      mkdir WebViewWindow/src/debug
                      touch WebViewWindow/src/debug/google-services.json
                      echo $GOOGLE_SERVICES_JSON >> WebViewWindow/src/debug/google-services.json

            - persist_to_workspace:
                root: /tmp/workspace
                paths:
                    - .

    build:
        <<: *defaults

        steps:
            - attach_workspace:
                at: /tmp/workspace

            - run:
                name: Run Debug Build
                command: ./gradlew assembleDebug

    test:
        <<: *defaults

        steps:
            - attach_workspace:
                at: /tmp/workspace

            - run:
                name: Run Test
                command: ./gradlew testDebug

            - run:
                name: Run Lint
                command: ./gradlew lintDebug

            - store_artifacts:
                path: build/reports

            - store_test_results:
                path: build/reports

workflows:
    sync_build_test:
        jobs:
            - sync
            - build:
                requires:
                    - sync
            - test:
                requires:
                    - build
