version: 2.1

jobs:
    sync:
        docker:
            - image: circleci/android:api-30-ndk

        steps:
            - checkout

    build:
        docker:
            - image: circleci/android:api-30-ndk

        steps:
            - run:
                name: Restore google-services.json
                command: |
                    mkdir WebViewWindow/src/debug
                    touch WebViewWindow/src/debug/google-services.json
                    echo $GOOGLE_SERVICES_JSON >> WebViewWindow/src/debug/google-services.json

            - run:
                name: Run Debug Build
                command: ./gradlew assembleDebug

    test:
        docker:
            - image: circleci/android:api-30-ndk

        steps:
            - run:
                name: Run Test
                command: ./gradlew test

            - run:
                name: Run Lint
                command: ./gradlew lint

            - store_artifacts:
                path: build/reports

            - store_test_results:
                path: build/reports

workflows:
    sync_build_test:
        jobs:
            - sync
            - build:
                requires:
                    - sync
            - test:
                requires:
                    - build
